<?php

$this->headTitle('Appointments');

?>

<div class="page-header">
  <h1>Appointments</h1>
</div>
<div class="row">
	<div class="col-lg-12" id="system-messages-container">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			
			<div class="panel-body">
			
                            <div id='calendar'></div>
	
			</div>
		</div>
	</div>
</div>

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_appointments', 'action' => 'add'), 'default', true);?>" id="add-appointment-dialog" class="modal fade form-horizontal" tabindex="-1" role="dialog">
  <input type="hidden" name="task" value="save">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add appointment for date: </h4>
      </div>
      <fieldset class="modal-body">
            <div class="form-group">
			<label class="col-md-3 control-label" for="date"> Date</label>
			<div class="col-md-9">
				<input type="text" name="date" id="date" class="form-control input-md" disabled>
                                <input type="hidden" name="date_hidden" id="date_hidden" class="form-control input-md">
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-3 control-label" for="first_name"> First Name</label>
			<div class="col-md-9">
				<input type="text" name="first_name" id="first_name" class="form-control input-md">
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-md-3 control-label" for="last_name"> Last Name</label>
			<div class="col-md-9">
				<input type="text" name="last_name" id="last_name" class="form-control input-md">
			</div>
		</div> 
          
                <div class="form-group">
			<label class="col-md-3 control-label" for="phone"> Phone</label>
			<div class="col-md-9">
				<input type="text" name="phone" id="phone" class="form-control input-md">
			</div>
		</div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="service">Select a service</label>
                    <div class="col-md-9">
                        <select id="service" name="service" class="form-control" style="text-align: center">
                            <option value=""><--- Select a service --></option>
                            <?php foreach($this->services as $service) { ?>
                            <option value="<?php echo $service['title'];?>"><?php echo $service['title'];?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
         </fieldset>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-save"></i> Save</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<form method="post" action="<?php echo $this->url(array('controller' => 'admin_appointments', 'action' => 'delete'), 'default', true);?>" id="delete-appointment-dialog" class="modal fade form-horizontal" tabindex="-1" role="dialog">
  <input type="hidden" name="task" value="delete">
  <input type="hidden" name="id" value="">
  
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete appointmetn: </h4>
      </div>
      <fieldset class="modal-body">
            <div class="form-group">
			<label class="col-md-3 control-label" for="date_d"> Date</label>
			<div class="col-md-9">
				<input type="text" name="date_d" id="date_d" class="form-control input-md" disabled>
                       </div>
		</div>
		<div class="form-group">
			<label class="col-md-3 control-label" for="title"> Title</label>
			<div class="col-md-9">
                            <input type="text" name="title" id="title" class="form-control input-md" disabled>
                       </div>
		</div>
		
         </fieldset>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<?php 
    $this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.css')); 
      //$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.min.css'));
     // $this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.print.css'));
      $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/lib/moment.min.js'));
      $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.js'));
      //$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/locale-all.js'));
      $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/locale/sr.js'));
      //$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/locale/sr-cyrl.js'));
     // $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.min.js'));
     // $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/lib/jquery-ui.min.js'));
?>

    
<script>
<?php $this->inlineScript()->captureStart(); ?>

$('[data-action="add-appointment"]').on('click', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		//select add photo dialog
		var addappDialog = $('#add-appointment-dialog');
		
		addappDialog.modal('show');
	});

$(document).ready(function() {

 $('#calendar').fullCalendar({
    header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay,listMonth'
    },
    navLinks: true, // can click day/week names to navigate views
    selectable: false,
    selectHelper: true,
    editable: false,
    defaultView: 'agendaWeek',
    minTime: '09:00:00',
    timezone: 'local',
    //timeFormat: 'H(:mm)',
    eventLimit: true, // allow "more" link when too many events
    events: '<?php echo $this->url(array('controller' => 'admin_appointments', 'action' => 'calendar'), 'default', true); ?>',
    dayClick: function(date, allDay, jsEvent, view) {   
        //select add photo dialog
        var d = new Date(date);
        var dd = moment(d).format('LLL');
        $('#date').val(dd);
        $('#date_hidden').val(date);
        
        var addappDialog = $('#add-appointment-dialog');
        addappDialog.modal('show');        
    },
    eventClick: function(calEvent, jsEvent, view) {
        
        var date = moment(calEvent.start).format('LLL');
        var title = calEvent.title;
        var id = calEvent.id;
        
        $('#date_d').val(date);
        $('#title').val(title);
        $('#delete-appointment-dialog').find('[name="id"]').val(id);
        
        
        var deleteappDialog = $('#delete-appointment-dialog');
        deleteappDialog.modal('show');
    }
 });
 
 });
<?php $this->inlineScript()->captureEnd(); ?>
</script>