<?php

$this->headTitle('Appointments');

?>

<div class="page-header">
  <h1>Appointments</h1>
</div>
<div class="row">
	<div class="col-lg-12" id="system-messages-container">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<button 
						data-action="add-appointment"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add Appointment</button>
				</div>
			</div>
			<div class="panel-body">
			
                            <div id='calendar'></div>
	
			</div>
		</div>
	</div>
</div>

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_apointments', 'action' => 'add'), 'default', true);?>" id="add-appointment-dialog" class="modal fade form-horizontal" tabindex="-1" role="dialog">
  <input type="hidden" name="task" value="save">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add appointment</h4>
      </div>
      <fieldset class="modal-body">
		<div class="form-group">
			<label class="col-md-3 control-label" for="first_name"> First Name</label>
			<div class="col-md-9">
				<input type="text" name="first_name" id="first_name" class="form-control input-md">
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-md-3 control-label" for="last_name"> Last Name</label>
			<div class="col-md-9">
				<input type="text" name="last_name" id="last_name" class="form-control input-md">
			</div>
		</div> 
          
                <div class="form-group">
			<label class="col-md-3 control-label" for="phone"> Phone</label>
			<div class="col-md-9">
				<input type="text" name="phone" id="phone" class="form-control input-md">
			</div>
		</div>
         </fieldset>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-save"></i> Save</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'delete'), 'default', true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete <span name="name"></span></h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete  <span name="name"></span>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->


<!--<div id="message-templates" style="display: none">
    <div data-container="message-box-success" class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>
    
    <div data-container="message-box-error" class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>
</div>-->
<?php $this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.css')); 
      //$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.min.css'));
     // $this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.print.css'));
      $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/lib/jquery.min.js'));
      $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/lib/moment.min.js'));
      $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.js'));
      //$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/locale-all.js'));
      $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/locale/sr.js'));
     // $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/fullcalendar.min.js'));
     // $this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/fullcalendar/lib/jquery-ui.min.js'));
       ?>

    
<script>
<?php $this->inlineScript()->captureStart(); ?>

$('[data-action="add-appointment"]').on('click', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		//select add photo dialog
		var addappDialog = $('#add-appointment-dialog');
		
		addappDialog.modal('show');
	});

$(document).ready(function() {

 $('#calendar').fullCalendar({
header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay,listMonth'
			},
 navLinks: true, // can click day/week names to navigate views
 selectable: true,
 selectHelper: true,
 editable: true,
 defaultView: 'agendaWeek',
 eventLimit: true, // allow "more" link when too many events
 events: '<?php echo $this->url(array('controller' => 'admin_appointments', 'action' => 'calendar'), 'default', true); ?>'
 });
 
 });
</script>
<?php $this->inlineScript()->captureEnd(); ?>
</script>