<?php

$categories = $this->categories;
$photos = $this->photos;
$indexSlides =$this->indexSlides;

?>

<!-- MAIN SLIDER : begin -->
			<div id="main-slider" class="m-has-hover-stop" data-interval="8000">
				<div class="slide-list">
                                    <?php foreach($indexSlides as $slide) { ?>
                                        
                                    <div class="slide slide-1 m-bg-align-right" data-label="<?php echo $this->escape($slide['title']); ?>" style="background-image: url( '<?php echo $this->indexSlideImgUrl($slide); ?>' );">
						<div class="slide-bg">
							<div class="container">
								<div class="slide-inner">
									<div class="slide-content various-content textalign-left valign-middle">

                                                                            <h2 style="font-size: 2em"><?php echo $this->escape($slide['title']); ?></h2>
                                                                                
                                                                                <?php if($slide['link_type'] != 'NoLink'){ ?>
                                                                                
                                                                                <h3 style="font-size: 1em">"><?php echo $this->escape($slide['description']); ?></h3>
                                                                        
                                                                                <a target="_blank"
                                                                                   href="<?php echo $this->indexSlideLinkUrl($slide); ?>"><?php echo $this->escape($slide['link_label']); ?></a>

                                                                                <?php } else{ ?>
                                                                                
										<h3 style="font-size: 1.5em"><?php echo $this->escape($slide['description']); ?></h3>
                                                                                
                                                                                <?php } ?>
									</div>
								</div>
							</div>
						</div>
					</div>
                                        
                                   <?php } ?>
					<!-- SLIDE 1 : begin -->
					<div class="slide slide-1 m-bg-align-right" data-label="Welcome to BEAUTYSPOT" style="background-image: url( '/front/images/slide_01.jpg' );">
						<div class="slide-bg">
							<div class="container">
								<div class="slide-inner">
									<div class="slide-content various-content textalign-left valign-middle">

										<h1>Welcome<br>to Be Beauty!</h1>
										<h3>Najbolji salon u kraju</h3>

									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- SLIDE 1 : end -->

					<!-- SLIDE 2 : begin -->
					<div class="slide slide-2 m-bg-align-left" data-label="20% off All Massages" style="background-image: url( '/front/images/slide_02.jpg' );">
						<div class="slide-bg">
							<div class="container">
								<div class="slide-inner">
									<div class="slide-content various-content textalign-right valign-middle">

										<h2>20% Off<br>All Massages</h2>
										<h3>This Friday Only!</h3>

									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- SLIDE 2 : end -->

					<!-- SLIDE 3 : begin -->
<!--					<div class="slide slide-3 m-bg-align-right" data-label="Eshop Launched" style="background-image: url( '/front/images/slide_03.jpg' );">
						<div class="slide-bg">
							<div class="container">
								<div class="slide-inner">
									<div class="slide-content various-content textalign-left valign-middle">

										<h2>Eshop<br>Launched</h2>
										<h3><a href="shop-list.html">Take a Look</a> at Our Products</h3>

									</div>
								</div>
							</div>
						</div>
					</div>-->
					<!-- SLIDE 3 : end -->

				</div>
			</div>
			<!-- MAIN SLIDER : end -->

			<!-- CORE : begin -->
			<div id="core">

				<!-- PAGE CONTENT : begin -->
				<div id="page-content">
					<div class="various-content">

						<!-- SERVICES SECTION : begin -->
						<section>

							<!-- SECTION HEADER : begin -->
							<header>
								<div class="container">
									<h2>Nase usluge</h2>
									<p class="subtitle">Nudimo Vam širok opseg usluga</p>
									<p class="more"><a href="<?php echo $this->sitemapPageUrl(5); ?>" class="c-button m-type-2">Pogledajte sve naše usluge</a></p>
								</div>
							</header>
							<!-- SECTION HEADER : end -->

							<!-- SERVICE LIST : begin -->
							<div class="c-service-list m-paginated" data-items="4" data-items-desktop="4" data-items-desktop-small="3" data-items-tablet="2" data-items-mobile="1">
								<div class="container">
									<div class="service-list-inner">
                                                                            <?php foreach($categories as $category) { ?>
										<div class="service-list-item">

											<!-- SERVICE : begin -->
											<div class="c-service">
												<div class="service-image">
                                                                                                    <a href="<?php echo $this->sitemapPageUrl(5); ?>#<?php echo $this->escape($category['title']);?>"><img src="<?php echo $this->categoryLeadingPhotoUrl($category);?>" title="<?php echo $this->categoryLeadingPhotoTitle($category); ?>" alt="<?php echo $this->escape($category['title']);?>"></a>
												</div>
												<h3 class="service-title"><a href="<?php echo $this->sitemapPageUrl(5); ?>#<?php echo $this->escape($category['title']);?>"><?php echo $this->escape($category['title']);?></a></h3>
<!--												<div class="service-description">
													<p>Facials, Eyebrow & Eyelashes, Microdermabrasion, Acne Treatments, Anti-Aging</p>
												</div>-->
											</div>
											<!-- SERVICE : end -->

										</div>
                                                                            
                                                                            <?php } ?>
                                                                            
										
									</div>
								</div>
							</div>
							<!-- SERVICE LIST : end -->

						</section>
						<!-- SERVICES SECTION : end -->

						<!-- GALLERY SECTION : begin -->
						<section>

							<!-- SECTION HEADER : begin -->
							<header>
								<div class="container">
									<h2>Galerija</h2>
									<p class="subtitle">Pogledajte neke od nasih slika</p>
									<p class="more"><a href="<?php echo $this->sitemapPageUrl(2); ?>" class="c-button m-type-2">Poseti galeriju</a></p>
								</div>
							</header>
							<!-- SECTION HEADER : end -->

							<!-- GALLERY : begin -->
							<div class="c-gallery m-paginated" data-items="4" data-items-desktop="4" data-items-desktop-small="3" data-items-tablet="2" data-items-mobile="1">
								<div class="thumb-list">
                                                                    <?php foreach($photos as $photo) { ?>
									<div class="thumb"><a href="<?php echo $this->photoUrl($photo);?>" class="lightbox" data-lightbox-group="gallery"><img src="<?php echo $this->photoUrl($photo);?>" title="<?php echo $this->categoryLeadingPhotoTitle($photo); ?>" alt="<?php echo $this->escape($photo['title']);?>"></a></div>
									
                                                                    <?php } ?>
                                                               </div>
							</div>
							<!-- GALLERY : end -->

						</section>
						<!-- GALLERY SECTION : end -->


						<!-- BRANDS SECTION : begin -->
						<section>

							<!-- SECTION HEADER : begin -->
							<header>
								<div class="container">
									<h2>Naši omiljeni brendovi</h2>
									<p class="subtitle">Mi koristimo samo najbolje</p>
								</div>
							</header>
							<!-- SECTION HEADER : end -->

							<div class="container">
								<div class="row">
									<div class="col-sm-3">
										<p class="textalign-center">

											<!-- BRAND LOGO : begin -->
											<a href="#" class="no-border"><img style="max-height: 140px;" src="/front/images/brand_01.jpg" alt=""></a>
											<!-- BRAND LOGO : end -->

										</p>
									</div>
									<div class="col-sm-3">
										<p class="textalign-center">

											<!-- BRAND LOGO : begin -->
											<a href="#" class="no-border"><img style="max-height: 140px;" src="/front/images/brand_02.png" alt=""></a>
											<!-- BRAND LOGO : end -->

										</p>
									</div>
									<div class="col-sm-3">
										<p class="textalign-center">

											<!-- BRAND LOGO : begin -->
											<a href="#" class="no-border"><img style="max-height: 140px;" src="/front/images/brand_03.png" alt=""></a>
											<!-- BRAND LOGO : end -->

										</p>
									</div>
									<div class="col-sm-3">
										<p class="textalign-center">

											<!-- BRAND LOGO : begin -->
											<a href="#" class="no-border"><img style="max-height: 140px;" src="/front/images/brand_04.png" alt=""></a>
											<!-- BRAND LOGO : end -->

										</p>
									</div>
								</div>
							</div>

						</section>
						<!-- BRANDS SECTION : end -->

					</div>
				</div>
				<!-- PAGE CONTENT : end -->

			</div>
			<!-- CORE : end -->

			