<?php

$this->headTitle('Filemanager');

?>
<div class="page-header">
	<h1>Filemanager</h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				
			</div>
			<div id="filemanager-container" class="panel-body">
				

			</div>
		</div>
	</div>
</div>
<?php
//jQuery UI
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));
//elFinder
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/elfinder/css/elfinder.min.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/elfinder/css/theme.css'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/elfinder/js/elfinder.min.js'));


?>
<script>
<?php $this->inlineScript()->captureStart();?>
	
	$('#filemanager-container').elfinder({
		url: '<?php echo $this->url(array('controller' => 'admin_filemanager', 'action' => 'connector'), 'default', true);?>'
	});
	
<?php $this->inlineScript()->captureEnd();?>
</script>