
<?php 

$this->headTitle('Services');

?>

<div class="page-header">
    <h1>Categories</h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <button data-action="save-order" class="btn btn-success" style="display: none;"><i class="glyphicon glyphicon-save"></i> Save order</button>
                    <button data-action="toggle-sort" class="btn btn-default"><i class="glyphicon glyphicon-list"></i> Change Order</button>
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_servicescategories', 'action' => 'add'), 'default', true); ?>" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i> Add category</a>
                </div>  
            </div>
            <div class="panel-body">
                <table id="rows-table" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="text-center">Img</th>
                            <th class="text-center">Status</th>
                            <th>Title</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->categories as $category){
                            
                            if($category['status'] == Application_Model_DbTable_CmsServicesCategories::STATUS_DISABLED){
                                ?>
                        <tr data-servicecategory-id="<?php echo $this->escape($category['id']); ?>" class="danger">
                            <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-move" style="display: none; cursor: pointer;"></i></td>
                            <td class="text-center"><img style="max-height: 50px;" src="<?php echo $this->categoryLeadingPhotoUrl($category);?>"></td>
                            <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                            <td><?php echo $this->escape($category['title']); ?></td>
                            <td class="text-center">
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'admin_servicescategories', 'action' => 'edit', 'id' => $category['id']), 'default', true); ?>"
                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <button data-serviceTitle="<?php echo $this->escape($category['title']); ?>" data-servicecategory-id="<?php echo $this->escape($category['id']); ?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                    <button data-serviceTitle="<?php echo $this->escape($category['title']); ?>" data-servicecategory-id="<?php echo $this->escape($category['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                </div>
                            </td>
                        </tr>
                            
                        <?php
                            } else{
                            ?>
                          <tr data-servicecategory-id="<?php echo $this->escape($category['id']); ?>">
                            <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-move" style="display: none; cursor: pointer;"></i></td>
                            <td class="text-center"><img style="max-height: 50px;" src="<?php echo $this->categoryLeadingPhotoUrl($category);?>"></td>
                            <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                            <td><?php echo $this->escape($category['title']); ?></td>
                            <td class="text-center">
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'admin_servicescategories', 'action' => 'edit', 'id' => $category['id']), 'default', true); ?>"
                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <button data-serviceTitle="<?php echo $this->escape($category['title']); ?>" data-servicecategory-id="<?php echo $this->escape($category['id']); ?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                    <button data-serviceTitle="<?php echo $this->escape($category['title']); ?>" data-servicecategory-id="<?php echo $this->escape($category['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                </div>
                            </td>
                        </tr>
                        
                        <?php
                            }
                        } 
                        ?>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_servicescategories', 'action' => 'delete'), 'default', true);?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete <span name="name"></span> service</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete <span name="name"></span> service?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_servicescategories', 'action' => 'disable'), 'default', true);?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable <span name="name"></span> service</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to disable <span name="name"></span> service?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_servicescategories', 'action' => 'enable'), 'default', true);?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enable service</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to enable <span name="name"></span> service?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-check"></i> Enable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<form id="save-order-form" method="post" action="<?php echo $this->url(array('controller' => 'admin_servicescategories', 'action' => 'updateorder'), 'default', true); ?>" style="display: none;">
    <input type="hidden" name="task" value="saveOrder">
    <input type="hidden" name="sorted_ids" value="">
    
</form>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css')); 
      $this->inlineScript()->appendFile('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js');  ?>
<script>
<?php $this->inlineScript()->captureStart(); ?>
    
 $(function () {
            $('[data-toggle="popover"]').popover({trigger: 'hover'});
              });

$(function () {
          $('[data-toggle="tooltip"]').tooltip();
              });    
    
$('#rows-table').on('click', '[data-action="delete"]', function(e) {
    e.preventDefault();
    e.stopPropagation();
    
    var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');
    
    var serviceId = target.attr('data-servicecategory-id');
      // get data- attributs
     // var memberId = target.data('service-id');
     
    var serviceTitle = target.attr('data-serviceTitle');
    
    
    $('#delete-warning-dialog').find('[name="id"]').val(serviceId);
    
    $('#delete-warning-dialog').find('[name="name"]').html(serviceTitle);
    
    $('#delete-warning-dialog').modal('show');
    
    
});

$('#rows-table').on('click', '[data-action="disable"]', function(e) {
    e.preventDefault();
    e.stopPropagation();
    
    var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
    
    var serviceId = target.attr('data-servicecategory-id');
      // get data- attributs
     // var memberId = target.data('service-id');
    
    var serviceTitle = target.attr('data-serviceTitle');
    
    $('#disable-warning-dialog').find('[name="id"]').val(serviceId);
    
    $('#disable-warning-dialog').find('[name="name"]').html(serviceTitle);
    
    $('#disable-warning-dialog').modal('show');
    
    
});

$('#rows-table').on('click', '[data-action="enable"]', function(e) {
    e.preventDefault();
    e.stopPropagation();
    
    var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');
    
    var serviceId = target.attr('data-servicecategory-id');
      // get data- attributs
     // var memberId = target.data('service-id');
    
    var serviceTitle = target.attr('data-serviceTitle');
    
    $('#enable-warning-dialog').find('[name="id"]').val(serviceId);
    
    $('#enable-warning-dialog').find('[name="name"]').html(serviceTitle);
    
    $('#enable-warning-dialog').modal('show');
    
});

$('[data-action="toggle-sort"]').on('click', function(e){
    e.preventDefault();
    e.stopPropagation();
    
    var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');
    
    var sortableTbody = $('#rows-table > tbody');
    
    if(target.hasClass('active')) {
        
        target.removeClass('active');
        
        target.html('<i class="glyphicon glyphicon-list"></i> Change order');
        
        // destroy sortable functionallity
        sortableTbody.sortable('destroy');
        
        // restore old html into tbody
        sortableTbody.html(sortableTbody.data('oldHtml'));
        
        //hide "handle" for sorting, the icon in first column
        sortableTbody.find('[data-action="sort"]').hide();
        
        // hide Save order button
        $('[data-action="save-order"').hide();
        
        
    } else {
        
        target.addClass('active');
        // method html sets or gets html inside selected element
        target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');
        
        // save tbody html before sorting under key "oldHtml" into its data
        sortableTbody.data('oldHtml', sortableTbody.html());
        
        sortableTbody.sortable({
            handle: '[data-action="sort"]'
        });
        
        
        //show "handle" for sorting, the icon in first column
        sortableTbody.find('[data-action="sort"]').show();
        
        // show Save order button
        $('[data-action="save-order"').show();
        
    }
});

$('[data-action="save-order"]').on('click', function(e){
    e.preventDefault();
    e.stopPropagation();
    
    var serviceSortedIds = $('#rows-table > tbody').sortable('toArray', {
        attribute: 'data-servicecategory-id'
    });
    
    // select save order
    var saveOrderForm = $('#save-order-form');
    
    // find element with name "sorted_ids" in save order form and set its value
    // with string in wich are sorted ids saparated with coma(,)
    // ex. "12,3,8,5,6,2"
    saveOrderForm.find('[name="sorted_ids"]').val(serviceSortedIds.join(','));
    
    // manually submit form by triggering "submit" event
    saveOrderForm.trigger('submit');
    
});

<?php $this->inlineScript()->captureEnd(); ?>
</script>