<?php

$sitemapPage = $this->sitemapPage;
$services = $this->services;
$categories = $this->categories;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('Description', $sitemapPage['description']);
$this->headMeta()->appendName('Keywords', 'manikir, pedikir, nokti, depilacija, masaža, solarijum');

?>

<!-- CORE : begin -->
			<div id="core" class="core-bg-1">

				<!-- PAGE HEADER : begin -->
				<div id="page-header">
					<div class="container">
						<h1><?php echo $this->escape($sitemapPage['title']); ?></h1>
                                                
						<?php echo $this->breadcrumbs($sitemapPage); ?>
					</div>
				</div>
				<!-- PAGE HEADER : begin -->

				<div class="container">

					<!-- PAGE CONTENT : begin -->
					<div id="page-content">
						<div class="various-content">
                                                   
                                                    <?php foreach($categories as $category ){ 
                                                        
                                                        if(count($services[$category['id']]) > 0) {
                                                        
                                                        ?>
                                                        <!-- CATEGORY SECTION : begin -->
							<section id="<?php echo $this->escape($category['title']);?>">

								<h2><?php echo $this->escape($category['title']);?></h2>
                                                                    <div class="row">
                                                                        
									<div class="col-sm-2">
                                                        		<!-- CATEGORY IMAGE : begin -->
                                                                        <p class="textalign-center margin-sides-auto max-width-180"><img src="<?php echo $this->categoryLeadingPhotoUrl($category);?>" title="<?php echo $this->categoryLeadingPhotoTitle($category); ?>" class="rounded" alt="<?php echo $this->escape($category['title']);?>"></p>
										<!-- CATEGORY IMAGE : end -->

									</div>
                                                                        
                                                                        <div class="col-sm-10">
                                                                        
                                                                <?php foreach($services[$category['id']] as $service) { 
                                                                    
                                                                    ?>
                                                                       
                                                                        <ul class="c-accordion">
                                                                            <li>
                                                                                <h3 class="accordion-title accordion-title-no-color"><?php echo $this->escape($service['title']);?></h3>
                                                                                     <p class="accordion-price"><?php echo $this->escape($service['price']);?> din</p>
                                                                                     
                                                                                     <?php if($service['description']) { ?>
                                                                                     
                                                                                     <div class="accordion-content">
                                                                                          <p><?php echo $this->escape($service['description']);?></p>
                                                                                     </div>
                                                                                     
                                                                                     <?php } ?>
                                                                            </li>
                                                                        </ul>                
                                                                    
                                                              <?php  
                                                                        }
                                                                        ?>
                                                                            
                                                                        </div>
                                                                        
                                                                     <?php   } ?>
                                                                            
                                                                  
								</div>
        
                                                             </section>           
                                                   <?php 
                                                        
                                                        } ?>
                                      
						</div>
					</div>
					<!-- PAGE CONTENT : end -->
                                
			</div>
			<!-- CORE : end -->
