<?php

$this->headTitle('PhotoGalleries - New Photo Gallery');

$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));

?>
<div class="page-header">
	<h1>PhotoGalleries <small>New Photo Gallery</small></h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_photogalleries', 'action' => 'index'), 'default', true);?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-arrow-left"></i> Back to all photoGalleries</a>
				</div>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
					<input type="hidden" name="task" value="save">
					<fieldset>

						<!-- Form Name -->
						<legend>New Photo Gallery</legend>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="title">Title</label>  
							<div class="col-md-4">
								<?php 
								echo $form->getElement('title')->setAttribs(array(
									'class' => 'form-control input-md',
									'placeholder' => 'enter photo gallery\'s title',
									'id' => 'title',
									'required' => 'required'
								));
								?>
								<span class="help-block">min 3 max 255 characters</span>  
							</div>
							<div class="col-md-4">
								<?php if ($form->getElement('title')->hasErrors()) {?>
								<div class="has-error">
									<?php foreach ($form->getElement('title')->getMessages() as $message) {?>
									<p class="help-block"><?php echo $this->escape($message);?></p>
									<?php }?>
								</div>
								<?php }?>
							</div>
						</div>

						<!-- Textarea -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="description">Description</label>
							<div class="col-md-4">
								<?php 
								echo $form->getElement('description')->setAttribs(array(
									'class' => 'form-control',
									'id' => 'description',
									'rows' => 12,
								));
								?>
							</div>
							
							<div class="col-md-4">
								<?php if ($form->getElement('description')->hasErrors()) {?>
								<div class="has-error">
									<?php foreach ($form->getElement('description')->getMessages() as $message) {?>
									<p class="help-block"><?php echo $this->escape($message);?></p>
									<?php }?>
								</div>
								<?php }?>
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label" for="photo_gallery_leading_photo">Leading Photo</label>
							<div class="col-md-4">
								
								<input type="file" name="photo_gallery_leading_photo" id="photo_gallery_leading_photo" class="form-control input-md">
							</div>
							
							<div class="col-md-4">
								<?php if ($form->getElement('photo_gallery_leading_photo')->hasErrors()) {?>
								<div class="has-error">
									<?php foreach ($form->getElement('photo_gallery_leading_photo')->getMessages() as $message) {?>
									<p class="help-block"><?php echo $this->escape($message);?></p>
									<?php }?>
								</div>
								<?php }?>
							</div>
						</div>
						<!-- Button (Double) -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="new_photoGallery_cancel"></label>
							<div class="col-md-8 text-right">
								<a href="<?php echo $this->url(array('controller' => 'admin_photogalleries', 'action' => 'index'), 'default', true);?>" id="new_photoGallery_cancel" name="new_photoGallery_cancel" class="btn btn-default">Cancel</a>
								<button type="submit" id="new_photoGallery_submit" name="new_photoGallery_submit" class="btn btn-success">Save</button>
							</div>
						</div>

					</fieldset>
				</form>

			</div>
		</div>
	</div>
</div>