<?php
$this->headTitle('Users');
?>
<div class="page-header">
	<h1>Users</h1>
</div>
<div class="row">
	<div class="col-lg-12" id="system-messages-container">
<?php echo $this->systemMessagesHtml($this->systemMessages); ?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'add'), 'default', true); ?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add user</a>
				</div>
			</div>
			<div class="panel-body">

				<table id="rows-table" class="table table-striped table-hover">
					<thead>
						<tr>
							<th class="text-center">Status</th>
							<th>Username</th>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
<?php /*
  foreach ($this->users as $user) {
  if ($user['status'] == Application_Model_DbTable_CmsUsers::STATUS_DISABLED) {
  ?>
  <tr data-user-id="<?php echo $this->escape($user['id']);?>" class="danger">
  <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
  <td><?php echo $this->escape($user['username']);?></td>
  <td><?php echo $this->escape($user['first_name']);?></td>
  <td><?php echo $this->escape($user['last_name']);?></td>
  <td><?php echo $this->escape($user['email']);?></td>
  <td class="text-center">
  <div class="btn-group btn-group-sm" role="group" aria-label="...">
  <a
  href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
  type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
  <button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
  <button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
  <button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="resetpassword" type="button" class="btn btn-default" title="reset password"><i class="fa fa-unlock-alt"></i></button>

  </div>
  </td>
  </tr>
  <?php
  } else {
  ?>
  <tr data-user-id="<?php echo $this->escape($user['id']);?>">
  <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
  <td><?php echo $this->escape($user['username']);?></td>
  <td><?php echo $this->escape($user['first_name']);?></td>
  <td><?php echo $this->escape($user['last_name']);?></td>
  <td><?php echo $this->escape($user['email']);?></td>
  <td class="text-center">
  <div class="btn-group btn-group-sm" role="group" aria-label="...">
  <a
  href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
  type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
  <button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disabled"><i class="glyphicon glyphicon-remove"></i></button>
  <button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
  <button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="resetpassword" type="button" class="btn btn-default" title="reset password"><i class="fa fa-unlock-alt"></i></button>

  </div>
  </td>
  </tr>
  <?php
  }
  ?>

  <?php
  }
 */ ?>

					</tbody>
				</table>



			</div>
		</div>
	</div>
</div>
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'delete'), 'default', true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Delete user</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete user?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"> </i>Delete</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'disable'), 'default', true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Disable user</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to disable user?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"> </i> Disable</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'enable'), 'default', true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Enable user</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to enable user?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"> </i> Enable</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'resetpassword'), 'default', true); ?>" id="resetpassword-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="resetPassword">
    <input type="hidden" name="id" value="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Reset user's password</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to reset user's password?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"> </i> Reset password</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<div id="message-templates" style="display: none">
	<div data-container="message-box-success" class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<span data-container="message-text"></span>
	</div>

	<div data-container="message-box-error" class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<span data-container="message-text"></span>
	</div>

</div>

<?php
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css'));
//$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/datatables-responsive/css/dataTables.responsive.css'));

$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables/media/js/jquery.dataTables.min.js'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/datatables-responsive/js/dataTables.responsive.js'));
?>
<script>
<?php $this->inlineScript()->captureStart(); ?>
	$('#rows-table').on('click', '[data-action="delete"]', function (e) {

		e.preventDefault();
		e.stopPropagation();


		var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');

		var userId = target.data('user-id');


		// set value for input field with name "id"
		$('#delete-warning-dialog').find('[name="id"]').val(userId);

		$('#delete-warning-dialog').modal('show');

	});

	$('#rows-table').on('click', '[data-action="disable"]', function (e) {

		e.preventDefault();
		e.stopPropagation();

		// calculate target element
		var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');

		// get any attribute
		var userId = target.attr('data-user-id');

		// set value for input field with name "id"
		$('#disable-warning-dialog').find('[name="id"]').val(userId);

		$('#disable-warning-dialog').modal('show');

	});

	$('#rows-table').on('click', '[data-action="enable"]', function (e) {

		e.preventDefault();
		e.stopPropagation();

		// calculate target element
		var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');

		// get any attribute
		var userId = target.attr('data-user-id');

		$('#enable-warning-dialog').find('[name="id"]').val(userId);

		$('#enable-warning-dialog').modal('show');

	});

	$('#rows-table').on('click', '[data-action="resetpassword"]', function (e) {

		e.preventDefault();
		e.stopPropagation();

		// calculate target element
		var target = $(this).is('[data-action="resetpassword"]') ? $(this) : $(this).closest('[data-action="resetpassword"]');

		// get any attribute
		var userId = target.attr('data-user-id');

		$('#resetpassword-warning-dialog').find('[name="id"]').val(userId);

		$('#resetpassword-warning-dialog').modal('show');

	});

	$('#rows-table').DataTable({
		columnDefs: [
			{targets: [5], orderable: false, searchable: false},
			{targets: [0, 5], className: 'text-center'}

		],
		order: [
			[2, 'asc']
		],
		lengthMenu: [3, 10, 20, 50, 100],
		serverSide: true,
		processing: true,
		ajax: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'datatable'), 'default', true); ?>'
	});

	$('#disable-warning-dialog').on('submit', function (e) {
		e.preventDefault(); //stop manual form submit

		var target = $(this).is('#disable-warning-dialog') ? $(this) : $(this).closest('#disable-warning-dialog');

		$.ajax({
			url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'disable'), 'default', true); ?>',
			method: 'post',
			data: {
				task: 'disable',
				id: target.find('[name="id"]').val()
			}

		}).done(function (data) {

			if (data['status'] === 'ok') {

				var messageBox = $('#message-templates [data-container="message-box-success"]').clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);
				
				//delay fadeout for 5000 milliseconds
				messageBox.delay(5000).fadeOut();

			} else {
				var messageBox = $('#message-templates').find('[data-container="message-box-error"]').last().clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);
				
				//delay fadeout for 5000 milliseconds
				messageBox.delay(5000).fadeOut();
			}

		}).fail(function () {
			//error in communication with server

			alert('Error: Server returned error');

		}).always(function () {

			target.modal('hide');
			//refresh table keep selected page
			$('#rows-table').DataTable().draw(false);
		});
	});
	
	
	$('#enable-warning-dialog').on('submit', function (e) {
		e.preventDefault(); //stop manual form submit

		var target = $(this).is('#enable-warning-dialog') ? $(this) : $(this).closest('#enable-warning-dialog');

		$.ajax({
			url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'enable'), 'default', true); ?>',
			method: 'post',
			data: {
				task: 'enable',
				id: target.find('[name="id"]').val()
			}

		}).done(function (data) {

			if (data['status'] === 'ok') {

				var messageBox = $('[data-container="message-box-success"]').last().clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);

			} else {
				var messageBox = $('[data-container="message-box-error"]').last().clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);

			}

		}).fail(function () {
			//error in communication with server

			alert('Error: Server returned error');

		}).always(function () {

			target.modal('hide');
			//refresh table keep selected page
			$('#rows-table').DataTable().draw(false);
		});
	});
	
	$('#delete-warning-dialog').on('submit', function (e) {
		e.preventDefault(); //stop manual form submit

		var target = $(this).is('#delete-warning-dialog') ? $(this) : $(this).closest('#delete-warning-dialog');

		$.ajax({
			url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'enable'), 'default', true); ?>',
			method: 'post',
			data: {
				task: 'delete',
				id: target.find('[name="id"]').val()
			}

		}).done(function (data) {

			if (data['status'] === 'ok') {

				var messageBox = $('[data-container="message-box-success"]').last().clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);

			} else {
				var messageBox = $('[data-container="message-box-error"]').last().clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);

			}

		}).fail(function () {
			//error in communication with server

			alert('Error: Server returned error');

		}).always(function () {

			target.modal('hide');
			//refresh table keep selected page
			$('#rows-table').DataTable().draw(false);
		});
	});
	
	$('#resetpassword-warning-dialog').on('submit', function (e) {
		e.preventDefault(); //stop manual form submit

		var target = $(this).is('#resetpassword-warning-dialog') ? $(this) : $(this).closest('#resetpassword-warning-dialog');

		$.ajax({
			url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'resetpassword'), 'default', true); ?>',
			method: 'post',
			data: {
				task: 'resetPassword',
				id: target.find('[name="id"]').val()
			}

		}).done(function (data) {

			if (data['status'] === 'ok') {

				var messageBox = $('[data-container="message-box-success"]').last().clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);


			} else {
				var messageBox = $('[data-container="message-box-error"]').last().clone(true);

				messageBox.find('[data-container="message-text"]').text(data['statusMessage']);

				$('#system-messages-container').append(messageBox);

			}

		}).fail(function () {
			//error in communication with server

			alert('Error: Server returned error');

		}).always(function () {

			target.modal('hide');
			//refresh table keep selected page
			$('#rows-table').DataTable().draw(false);
		});
	});

<?php $this->inlineScript()->captureEnd(); ?>
</script>