<?php
$user = Zend_Auth::getInstance()->getIdentity();
?>
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <?php echo $this->headTitle('Cubes School Admin')->setSeparator(' | ');?>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $this->baseUrl('/admin/bower_components/bootstrap/dist/css/bootstrap.min.css');?>" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?php echo $this->baseUrl('/admin/bower_components/metisMenu/dist/metisMenu.min.css');?>" rel="stylesheet">

    <?php echo $this->headLink();?>
	
    <!-- Custom CSS -->
    <link href="<?php echo $this->baseUrl('/admin/dist/css/sb-admin-2.css');?>" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $this->baseUrl('/admin/bower_components/font-awesome/css/font-awesome.min.css');?>" rel="stylesheet" type="text/css">
	
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<?php echo $this->headScript();?>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'admin_dashboard'), 'default', true);?>">Cubes School Admin</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
						<li><a href="#">Signed in as <strong><?php echo $this->escape($user['username']);?></strong></a></li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'admin_profile', 'action' => 'edit'), 'default', true);?>"><i class="fa fa-user fa-fw"></i> Edit Profile</a>
                        </li>
                        <li><a href="<?php echo $this->url(array('controller' => 'admin_profile', 'action' => 'changepassword'), 'default', true);?>"><i class="fa fa-key fa-fw"></i> Change Password</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'admin_session', 'action' => 'logout'), 'default', true);?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'admin_dashboard'), 'default', true);?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('controller' => 'admin_indexslides'), 'default', true);?>"><i class="fa fa-sliders fa-fw"></i> Index Slider</a>
                        </li>
						<li>
                            <a href="<?php echo $this->url(array('controller' => 'admin_photogalleries'), 'default', true);?>"><i class="fa fa-photo fa-fw"></i> Photo Galleries</a>
                        </li>
						<li>
                            <a href="<?php echo $this->url(array('controller' => 'admin_sitemap'), 'default', true);?>"><i class="fa fa-sitemap fa-fw"></i> Sitemap</a>
                        </li>
						<li>
                            <a href="<?php echo $this->url(array('controller' => 'admin_filemanager'), 'default', true);?>"><i class="fa fa-files-o fa-fw"></i> Filemanager</a>
                        </li>
						<li>
                            <a href="<?php echo $this->url(array('controller' => 'admin_users'), 'default', true);?>"><i class="fa fa-user fa-fw"></i> Users</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                
				<?php echo $this->layout()->content;?>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="<?php echo $this->baseUrl('/admin/bower_components/jquery/dist/jquery.min.js');?>"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->baseUrl('/admin/bower_components/bootstrap/dist/js/bootstrap.min.js');?>"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?php echo $this->baseUrl('/admin/bower_components/metisMenu/dist/metisMenu.min.js');?>"></script>

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo $this->baseUrl('/admin/dist/js/sb-admin-2.js');?>"></script>
	
	<?php echo $this->inlineScript();?>
</body>

</html>

