<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<?php echo $this->headTitle('BeBeauty')->setSeparator(' | ');?>
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- @todo: fill with your company info or remove -->
		<?php echo $this->headMeta();?>
                
		<!-- General CSS -->
                
		<!-- STYLESHEETS : begin -->
                <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/front/library/css/style.css'); ?>">
                <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/front/library/css/skin/lavender.css'); ?>">
                <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/front/library/css/custom.css'); ?>">
                <!-- STYLESHEETS : end -->
                
		<?php echo $this->headLink();?>
		<!-- Theme  CSS -->
		
                
                <!--[if lte IE 8]>
                                <link rel="stylesheet" type="text/css" href="/front/library/css/oldie.css">
                                <script src="<?php echo $this->baseUrl('/front/library/js/respond.min.js'); ?>" type="text/javascript"></script>
                <![endif]-->
                
		<?php echo $this->headStyle();?>
		
		<?php echo $this->headScript();?>
                
                <link rel="shortcut icon" href="/front/images/favicon.ico">
                
                <!-- GOOGLE FONTS : begin -->
                <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700%7cMontserrat:400,700&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
                <!-- GOOGLE FONTS : end -->

                

                
                <script src="/front/library/js/modernizr.custom.min.js" type="text/javascript"></script>
                
	</head>

	<!-- ======== @Region: body ======== -->
	<body>
            
            <header id="header" class="m-animated">
			<div class="header-bg">
				<div class="header-inner">

					<!-- HEADER BRANDING : begin -->
					<div class="header-branding">
						<a href="<?php echo $this->baseUrl('/'); ?>"><img src="/front/images/logo.png" alt="BeBeauty" data-hires="/front/images/logo.2x.png" width="291"></a>
					</div>
					<!-- HEADER BRANDING : end -->

					<!-- HEADER NAVIGATION : begin -->
					<div class="header-navigation">

						<!-- HEADER MENU : begin -->
						<nav class="header-menu">
							<button class="header-menu-toggle" type="button"><i class="fa fa-bars"></i>MENU</button>
							<ul>
                                                            <?php
                                                                $activePage = $this->activePage;
                                                            ?>
								<li <?php echo ($activePage == 'index') ? 'class="m-active"' : '';  ?>>
									<span><a href="<?php echo $this->baseUrl('/'); ?>">Naslovna strana</a></span>
								</li>
                                                                
                                                                <?php echo $this->topMenuHtml(); ?>
							</ul>
						</nav>
						<!-- HEADER MENU : end -->

						
					</div>
					<!-- HEADER NAVIGATION : end -->

					<!-- HEADER PANEL : begin -->
					<div class="header-panel">

						<button class="header-panel-toggle" type="button"><i class="fa"></i></button>

<!--						 HEADER RESERVATION : begin 
						<div class="header-reservation">
							<a href="ajax/reservation-form.html" class="c-button m-open-ajax-modal">Make a Reservation</a>
						</div>
						 HEADER RESERVATION : end -->

						<!-- HEADER CONTACT : begin -->
						<div class="header-contact">
							<ul>

								<!-- PHONE : begin -->
								<li>
									<div class="item-inner">
										<i class="ico fa fa-phone"></i>
										<strong>+381 11 3494 929</strong>
									</div>
								</li>
                                                                
                                                                <li>
									<div class="item-inner">
										<i class="ico fa fa-phone"></i>
										<strong>+381 64 3494 929</strong>
									</div>
								</li>
								<!-- PHONE : end -->

								<!-- EMAIL : begin -->
								<li>
									<div class="item-inner">
										<i class="ico fa fa-envelope-o"></i>
										<a href="mailto:">bebeautybyjecaisanja@gmail.com</a>
									</div>
								</li>
								<!-- EMAIL : end -->

								<!-- ADDRESS : begin -->
								<li>
									<div class="item-inner">
										<i class="ico fa fa-map-marker"></i>
										<strong>BE BEAUTY</strong><br>
										Milana Rakića 120<br>
										Beograd
									</div>
								</li>
								<!-- ADDRESS : end -->

								<!-- HOURS : begin -->
								<li>
									<div class="item-inner">
										<i class="ico fa fa-clock-o"></i>
										<dl>
											<dt>Pon. - Pet.:</dt>
											<dd>09:00 - 21:00</dd>
											<dt>Sub.:</dt>
											<dd>10:00 - 19:00</dd>
											<dt>Ned.:</dt>
											<dd>Zatvoreno</dd>
										</dl>
									</div>
								</li>
								<!-- HOURS : end -->

							</ul>
						</div>
						<!-- HEADER CONTACT : end -->

						<!-- HEADER SOCIAL : begin -->
						<div class="header-social">
							<ul>
								<li><a href="https://www.facebook.com/SalonLepoteBeBeauty/" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                                                <li><a href="https://www.instagram.com/salon_bebeauty_mirijevo/" title="Instagram" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
						<!-- HEADER SOCIAL : end -->

					</div>
					<!-- HEADER PANEL : end -->

				</div>
			</div>
		</header>
            <!-- WRAPPER : begin -->
		<div id="wrapper">

		<?php echo $this->layout()->content;?>
            
            <!-- BOTTOM PANEL : begin -->
			<div id="bottom-panel">
				<div class="bottom-panel-inner">
					<div class="container">
						<div class="row">
							<div class="col-md-6">
                                                            <div class="footer-text" style="float: left; padding-top: 150px;">
                                                                <p class="">Ovaj projekat je realizovan u okviru <a href="http://school.cubes.rs" target="_blank">CUBES SCHOOL</a>
                                                                        <br> 
                                                                        Projekat realizovao: Miloš Stefanović </p>
                                                                </div>
							</div>
							<div class="col-md-6">

								<!-- BOTTOM SUBSCRIBE : begin -->
								<div class="bottom-subscribe various-content">

									<h3>Newsletter</h3>
									<p>BEAUTYSPOT supports MailChimp integration.</p>
									<form id="subscribe-form" action="http://volovar.us8.list-manage.com/subscribe/post-json?u=76a50c9454ec8ab78914d1bf2&amp;id=49e892f53d&amp;c=?" method="get">

										<!-- VALIDATION ERROR MESSAGE : begin -->
										<p style="display: none;" class="c-alert-message m-warning m-validation-error"><i class="ico fa fa-exclamation-circle"></i>Email address is required.</p>
										<!-- VALIDATION ERROR MESSAGE : end -->

										<!-- SENDING REQUEST ERROR MESSAGE : begin -->
										<p style="display: none;" class="c-alert-message m-warning m-request-error"><i class="ico fa fa-exclamation-circle"></i>There was a connection problem. Try again later.</p>
										<!-- SENDING REQUEST ERROR MESSAGE : end -->

										<!-- SUCCESS MESSAGE : begin -->
										<p style="display: none;" class="c-alert-message m-success"><i class="ico fa fa-check-circle"></i><strong>Sent successfully.</strong></p>
										<!-- SUCCESS MESSAGE : end -->

										<div class="form-fields">
											<input class="m-required m-email" name="EMAIL" type="text" data-placeholder="Your email address" title="Your email address">
											<button class="c-button submit-btn" type="submit" data-label="Subscribe" data-loading-label="Sending...">Subscribe</button>
										</div>
									</form>
                                                                        <nav class="footer-menu">
                                                                            <ul>
										<li><a href="<?php echo $this->sitemapPageUrl(4); ?>">O nama</a></li>
										<li><a href="<?php echo $this->sitemapPageUrl(6); ?>">Kontakt</a></li>
									</ul>
                                                                        </nav>
                                                                </div>
								<!-- BOTTOM SUBSCRIBE : end -->

							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- BOTTOM PANEL : end -->
          
                    </div>
		<!-- WRAPPER : end -->
		
		<!-- SCRIPTS : begin -->
		<script src="<?php echo $this->baseUrl('/front/library/js/jquery-1.9.1.min.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('/front/library/js/jquery-ui-1.10.4.custom.min.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('/front/library/js/jquery.ba-outside-events.min.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('/front/library/js/owl.carousel.min.js'); ?>" type="text/javascript"></script><!-- Carousel -->
		<script src="<?php echo $this->baseUrl('/front/library/js/jquery.magnific-popup.min.js'); ?>" type="text/javascript"></script><!-- Lightbox -->
		<script src="<?php echo $this->baseUrl('/front/library/js/library.js'); ?>" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl('/front/library/js/scripts.js'); ?>" type="text/javascript"></script>
		<!-- SCRIPTS : end -->
                
		<?php echo $this->inlineScript();?>
	</body>

</html>
