<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<?php echo $this->headTitle('PROJECT NAME')->setSeparator(' | ');?>
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- @todo: fill with your company info or remove -->
		<?php echo $this->headMeta();?>
		<!-- General CSS -->
		
		<?php echo $this->headLink();?>
		<!-- Theme  CSS -->
		
		<?php echo $this->headStyle();?>
		
		<?php echo $this->headScript();?>
	</head>

	<!-- ======== @Region: body ======== -->
	<body>

		<?php echo $this->layout()->content;?>
		
		<!--Scripts -->
		<?php echo $this->inlineScript();?>
	</body>

</html>
