<?php

$this->headTitle('Index Slider');

?>
<div class="page-header">
  <h1>IndexSlides</h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<button
						data-action="save-order"
						class="btn btn-success"
						style="display: none;"
					>
						<i class="glyphicon glyphicon-save"></i>
						Save Order
					</button>
					<button
						data-action="toggle-sort"
						class="btn btn-default"
					>
						<i class="glyphicon glyphicon-list"></i>
						Change Order
					</button>
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_indexslides', 'action' => 'add'), 'default', true);?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add Index Slide</a>
				</div>
			</div>
			<div class="panel-body">
				
				<table id="rows-table" class="table table-striped table-hover">
					<thead>
						<tr>
							<th></th>
							<th class="text-center">Img</th>
							<th class="text-center">Status</th>
							<th>Title</th>
							<th>Link Type</th>
							<th>Link</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
						<?php 
						foreach ($this->indexSlides as $indexSlide) {
							if ($indexSlide['status'] == Application_Model_DbTable_CmsIndexSlides::STATUS_DISABLED) {
							?>
						<tr data-index-slide-id="<?php echo $this->escape($indexSlide['id']);?>" class="danger">
							<td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list"  style="display: none; cursor: pointer;"></i></td>
							<td class="text-center"><img style="max-height: 60px;" src="<?php echo $this->indexSlideImgUrl($indexSlide);?>"></td>
							<td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
							<td><?php echo $this->escape($indexSlide['title']);?></td>
							<td><?php echo $this->escape($indexSlide['link_type']);?></td>
							<td>
								<?php if ($indexSlide['link_type'] != 'NoLink') {?>
								<a
									target="_blank"
									href="<?php echo $this->indexSlideLinkUrl($indexSlide);?>"
									><?php echo $this->escape($indexSlide['link_label']);?></a>
								<?php }?>
							</td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
										href="<?php echo $this->url(array('controller' => 'admin_indexslides', 'action' => 'edit', 'id' => $indexSlide['id']), 'default', true);?>"
										type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button data-index-slide-id="<?php echo $this->escape($indexSlide['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
									<button data-index-slide-id="<?php echo $this->escape($indexSlide['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								
								</div>
							</td>
						</tr>
							<?php
							} else {
							?>
						<tr data-index-slide-id="<?php echo $this->escape($indexSlide['id']);?>">
							<td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor: pointer;"></i></td>
							<td class="text-center"><img style="max-height: 60px;" src="<?php echo $this->indexSlideImgUrl($indexSlide);?>"></td>
							<td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
							<td><?php echo $this->escape($indexSlide['title']);?></td>
							<td><?php echo $this->escape($indexSlide['link_type']);?></td>
							<td>
								<?php if ($indexSlide['link_type'] != 'NoLink') {?>
								<a
									target="_blank"
									href="<?php echo $this->indexSlideLinkUrl($indexSlide);?>"
									><?php echo $this->escape($indexSlide['link_label']);?></a>
								<?php }?>
							</td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
										href="<?php echo $this->url(array('controller' => 'admin_indexslides', 'action' => 'edit', 'id' => $indexSlide['id']), 'default', true);?>"
										type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button data-index-slide-id="<?php echo $this->escape($indexSlide['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
									<button data-index-slide-id="<?php echo $this->escape($indexSlide['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								</div>
							</td>
						</tr>
							<?php
							}
							?>
						
							<?php
						}
						?>
						
					</tbody>
				</table>
				
				
				
			</div>
		</div>
	</div>
</div>

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_indexslides', 'action' => 'delete'), 'default', true);?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
	<input type="hidden" name="task" value="delete">
	<input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete indexSlide</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete indexSlide?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_indexslides', 'action' => 'disable'), 'default', true);?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
	<input type="hidden" name="task" value="disable">
	<input type="hidden" name="id" value="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable indexSlide</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to disable indexSlide?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_indexslides', 'action' => 'updateorder'), 'default', true);?>" style="display: none;" id="save-order-form">
	<input type="hidden" name="task" value="saveOrder">
	<input type="hidden" name="sorted_ids" value="">
</form>
<?php
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));
$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));
?>
<script>
<?php $this->inlineScript()->captureStart(); ?>
	
	$('#rows-table').on('click', '[data-action="delete"]', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		//calculate target element
		var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');
		
		//get any attribute
		var indexSlideId = target.attr('data-index-slide-id');
		
		//get data- attributes
		var indexSlideId = target.data('index-slide-id');
		
		
		//set value for input field with name "id"
		$('#delete-warning-dialog').find('[name="id"]').val(indexSlideId);
		
		$('#delete-warning-dialog').modal('show');
	});
	
	$('#rows-table').on('click', '[data-action="disable"]', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		//calculate target element
		var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
		
		//get any attribute
		var indexSlideId = target.attr('data-index-slide-id');
		
		//get data- attributes
		//var indexSlideId = target.data('indexSlideId');
		
		
		//set value for input field with name "id"
		$('#disable-warning-dialog').find('[name="id"]').val(indexSlideId);
		
		$('#disable-warning-dialog').modal('show');
	});
	
	$('[data-action="toggle-sort"]').on('click', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');
		
		var sortableTbody = $('#rows-table > tbody');
		
		if (target.hasClass('active')) {
			
			target.removeClass('active');
			
			target.html('<i class="glyphicon glyphicon-list"></i> Change Order');
			
			// destroy sortable functionallity
			sortableTbody.sortable('destroy');
			
			// restore old html into tbody
			sortableTbody.html(sortableTbody.data('oldHtml'));
			
			//hide "handle" for sorting, the icon in first column
			sortableTbody.find('[data-action="sort"]').hide();
			
			//hide "Save Order" button
			$('[data-action="save-order"]').hide();
			
		} else {
			
			target.addClass('active');
			
			//method html sets or gets html inside selected element
			target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');
			
			//save tbody html before sorting under key "oldHtml" into its data
			sortableTbody.data('oldHtml', sortableTbody.html());
			
			//initialize sortable functionallity
			sortableTbody.sortable({
				handle: '[data-action="sort"]'
			});
			
			//show "handle" for sorting, the icon in first column
			sortableTbody.find('[data-action="sort"]').show();
			
			//show "Save Order" button
			$('[data-action="save-order"]').show();
		}
	});
	
	$('[data-action="save-order"]').on('click', function(e) {
		
		e.preventDefault();
		e.stopPropagation();
		
		var indexSlideSortedIds = $('#rows-table > tbody').sortable('toArray', {
			attribute: 'data-index-slide-id'
		});
		
		//select save order form
		var saveOrderForm = $('#save-order-form');
		
		//find element with name "sorted_ids" in save order form and set its value
		// with string in wich are sorted ids separated with coma (,)
		// ex. "12,3,8,10,11,6,2,1,9,7,5,4"
		saveOrderForm.find('[name="sorted_ids"]').val(indexSlideSortedIds.join(','));
		
		// manually submit form by triggering "submit" event
		saveOrderForm.trigger('submit');
	});
	
<?php $this->inlineScript()->captureEnd(); ?>
</script>