<?php

$sitemapPage = $this->sitemapPage;
$systemMessagesForContact = $this->systemMessagesForContact;
$systemMessages = $this->systemMessages;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('Description', $sitemapPage['description']);
$this->headMeta()->appendName('Keywords', 'manikir, pedikir, nokti, depilacija, masaža, solarijum');
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));

?>

<!-- CORE : begin -->
			<div id="core">

				<!-- PAGE HEADER : begin -->
				<div id="page-header">
					<div class="container">
						<h1><?php echo $this->escape($sitemapPage['title']); ?></h1>
						<?php echo $this->breadcrumbs($sitemapPage); ?>
					</div>
				</div>
				<!-- PAGE HEADER : begin -->

				<div class="container">

					<!-- PAGE CONTENT : begin -->
					<div id="page-content">
						<div class="various-content">

							<!-- ADDRESS SECTION : begin -->
							<section>

								<h2>Gde nas možete pronaći</h2>

								<div class="row">
									<div class="col-lg-8">

										<!-- MAP : begin -->
										<div class="c-map">
											<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2831.4648909420875!2d20.5198515381079!3d44.791713535927784!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ssr!2srs!4v1473262527219" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
										</div>
										<!-- MAP : end -->

									</div>
									<div class="col-lg-4">

										<p> Na mapi je prikazana tačna lokacija našeg salone.</p>

                                                                                <!-- ICON BLOCK : begin -->
										<div class="c-icon-block">
											<i class="ico fa fa-map-marker"></i>
											<div class="icon-block-inner">
												<p>
													<strong>BE BEAUTY - Adresa</strong><br>
													Milana Rakića 120<br>
                                                                                                        Beograd
												</p>
											</div>
										</div>
										<!-- ICON BLOCK : end -->
                                                                                
                                                                                <!-- ICON BLOCK : begin -->
										<div class="c-icon-block">
											<i class="ico fa fa-phone"></i>
											<div class="icon-block-inner">
												<p>
													<strong>Telefoni za zakazivanje</strong><br>
													+381 64 3494 929<br>
                                                                                                        +381 11 3423 979
												</p>
											</div>
										</div>
										<!-- ICON BLOCK : end -->

										<!-- ICON BLOCK : begin -->
										<div class="c-icon-block">
											<i class="ico fa fa-clock-o"></i>
											<div class="icon-block-inner">
                                                                                             <?php if($sitemapPage['body']) { 
                                                                                                 
                                                                                                    echo $sitemapPage['body'] ;
                                                                                                   
                                                                                            } ?>
                                                                                            
											</div>
										</div>
										<!-- ICON BLOCK : end -->

									</div>
								</div>

							</section>
							<!-- ADDRESS SECTION : end -->

							<!-- FORM SECTION : begin -->
							<section>
                                                           
								<h2>Pošaljite nam poruku</h2>

								<div class="row">
									<div class="col-lg-8">
                                                                            
                                                                          <?php  if($systemMessagesForContact == 'init'){ ?>
                                                                            
                                                                            				<!-- CONTACT FORM : begin -->
										<form id="contact-form" class="default-form" method="post" action="">
											<input type="hidden" name="task" value="contact">
<!--
											 FORM VALIDATION ERROR MESSAGE : begin 
											<p class="c-alert-message m-warning m-validation-error" style="display: none;"><i class="ico fa fa-exclamation-circle"></i>Molimo Vas popunite sva obavezna (*) polja.</p>
											 FORM VALIDATION ERROR MESSAGE : end 

											 SENDING REQUEST ERROR MESSAGE : begin 
											<p class="c-alert-message m-warning m-request-error" style="display: none;"><i class="ico fa fa-exclamation-circle"></i>There was a connection problem. Try again later.</p>
											 SENDING REQUEST ERROR MESSAGE : end 
                                                                                        -->
											<div class="row">
												<div class="col-sm-6">

													<!-- NAME FIELD : begin -->
													<div class="form-field">
														<label for="contact-name">Vaše ime <span>*</span></label>
                                                                                                                 <?php
                                                                                                                echo $form->getElement('first_name')->setAttribs(array(
                                                                                                                    'class' => 'm-required',
                                                                                                                    'id' => 'contact-name'
                                                                                                                ));
                                                                                                                ?>
													</div>
													<!-- NAME FIELD : end -->
                                                                                                        <br>
                                                                                                         <?php if ($form->getElement('first_name')->hasErrors()) { ?>
                                                                                                                        <p class="c-alert-message m-warning">
                                                                                                                            <?php foreach ($form->getElement('first_name')->getMessages() as $message) { ?>
                                                                                                                                <i class="ico fa fa-exclamation-circle"></i><?php echo $this->escape($message); ?>
                                                                                                                            <?php } ?>
                                                                                                                         </p>
                                                                                                                    <?php } ?>
                                                                                                                                
                                                                                                        <!-- EMAIL FIELD : begin -->
													<div class="form-field">
														<label for="contact-email">Vaša Email Adresa <span>*</span></label>
                                                                                                                 <?php
                                                                                                                echo $form->getElement('email')->setAttribs(array(
                                                                                                                    'class' => 'm-required m-email',
                                                                                                                    'id' => 'contact-email'
                                                                                                                ));
                                                                                                                ?>
													</div>
                                                                                                        <p style="display: none;">
														<label for="contact-email-hp">Re Email Address</label>
														<input id="contact-email-hp" name="contact-email-hp">
													</p>
													<!-- EMAIL FIELD : end -->
                                                                                                        <br>
                                                                                                         <?php if ($form->getElement('email')->hasErrors()) { ?>
                                                                                                                        <p class="c-alert-message m-warning">
                                                                                                                            <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                                                                                                                <i class="ico fa fa-exclamation-circle"></i><?php echo $this->escape($message); ?>
                                                                                                                            <?php } ?>
                                                                                                                         </p>
                                                                                                                    <?php } ?>
                                                                                                      
                                                                                                                         
                                                                                                        <!-- PHONE FIELD : begin -->
													<div class="form-field">
														<label for="contact-phone">Vaš broj telefona </label>
                                                                                                                 <?php
                                                                                                                echo $form->getElement('phone')->setAttribs(array(
                                                                                                                    'id' => 'contact-phone'
                                                                                                                ));
                                                                                                                ?>
													</div>
													<!-- PHONE FIELD : end -->
                                                                                                        <br>
                                                                                                         <?php if ($form->getElement('phone')->hasErrors()) { ?>
                                                                                                                        <p class="c-alert-message m-warning">
                                                                                                                            <?php foreach ($form->getElement('phone')->getMessages() as $message) { ?>
                                                                                                                                <i class="ico fa fa-exclamation-circle"></i><?php echo $this->escape($message); ?>
                                                                                                                            <?php } ?>
                                                                                                                         </p>
                                                                                                                    <?php } ?>
												</div>
												<div class="col-sm-6">

													<!-- SUBJECT FIELD : begin -->
                                                                                                        <div class="form-field">
														<label for="contact-subject">Naslov poruke </label>
                                                                                                                 <?php
                                                                                                                echo $form->getElement('subject')->setAttribs(array(
                                                                                                                    'id' => 'contact-subject'
                                                                                                                ));
                                                                                                                ?>
													</div>
													<!-- SUBJECT FIELD : end -->
                                                                                                        <br>
                                                                                                         <?php if ($form->getElement('subject')->hasErrors()) { ?>
                                                                                                                        <p class="c-alert-message m-warning">
                                                                                                                            <?php foreach ($form->getElement('subject')->getMessages() as $message) { ?>
                                                                                                                                <i class="ico fa fa-exclamation-circle"></i><?php echo $this->escape($message); ?>
                                                                                                                            <?php } ?>
                                                                                                                         </p>
                                                                                                                    <?php } ?>
                                       
													<!-- MESSAGE FIELD : begin -->
                                                                                                        <div class="form-field">
														<label for="contact-message">Poruka <span>*</span></label>
                                                                                                                 <?php
                                                                                                                echo $form->getElement('message')->setAttribs(array(
                                                                                                                    'class' => 'm-required',
                                                                                                                    'id' => 'contact-message',
                                                                                                                    'rows' => 12,
                                                                                                                ));
                                                                                                                ?>
													</div>
													<!-- MESSAGE FIELD : end -->
                                                                                                        <br>
                                                                                                         <?php if ($form->getElement('message')->hasErrors()) { ?>
                                                                                                                        <p class="c-alert-message m-warning">
                                                                                                                            <?php foreach ($form->getElement('message')->getMessages() as $message) { ?>
                                                                                                                                <i class="ico fa fa-exclamation-circle"></i><?php echo $this->escape($message); ?>
                                                                                                                            <?php } ?>
                                                                                                                         </p>
                                                                                                                    <?php } ?>
                                          
													<!-- SUBMIT BUTTON : begin -->
													<div class="form-field">
														<button class="submit-btn c-button" type="submit" data-label="Send Message" data-loading-label="Slanje...">Pošalji poruku</button>
													</div>
													<!-- SUBMIT BUTTON : end -->

												</div>
											</div>

										</form>
										<!-- CONTACT FORM : end -->

                                                                          <?php 
                                                                          
                                                                             } else {
                                                                                    if($systemMessagesForContact == 'Error'){ ?>
                                                                                
                                                                                        <p class="c-alert-message m-warning"><i class="ico fa fa-exclamation-circle"></i>Doslo je do greske prilikom slanja poruke</p>
                                                                                        
                                                                                   <?php } else { ?>
                                                                                        
                                                                                        <p class="c-alert-message m-success"><i class="ico fa fa-check-circle"></i>Uspesno poslata poruka</p>
                                                                                  
                                                                                     <?php }
                                                                                }
                                                                            ?>  

						
									</div>
									
								</div>

							</section>
							<!-- FORM SECTION : end -->

						</div>
					</div>
					<!-- PAGE CONTENT : end -->

				</div>

			</div>
			<!-- CORE : end -->