<?php

$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('Description', $sitemapPage['description']);
$this->headMeta()->appendName('Keywords', 'manikir, pedikir, nokti, depilacija, masaža, solarijum');
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));

?>

<!-- CORE : begin -->
			<div id="core">

				<!-- PAGE HEADER : begin -->
				<div id="page-header">
					<div class="container">
						<h1><?php echo $this->escape($sitemapPage['title']); ?></h1>
						<?php echo $this->breadcrumbs($sitemapPage); ?>
					</div>
				</div>
				<!-- PAGE HEADER : begin -->

				<div class="container">

					<!-- PAGE CONTENT : begin -->
					<div id="page-content">
						<div class="various-content">

							<!-- ADDRESS SECTION : begin -->
							<section>

								<h2>Gde nas možete pronaći</h2>

								<div class="row">
									<div class="col-lg-8">

										<!-- MAP : begin -->
										<div class="c-map">
											<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2831.4648909420875!2d20.5198515381079!3d44.791713535927784!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ssr!2srs!4v1473262527219" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
										</div>
										<!-- MAP : end -->

									</div>
									<div class="col-lg-4">

										<p> Na mapi je prikazana tačna lokacija našeg salone.</p>

                                                                                <!-- ICON BLOCK : begin -->
										<div class="c-icon-block">
											<i class="ico fa fa-map-marker"></i>
											<div class="icon-block-inner">
												<p>
													<strong>BE BEAUTY - Adresa</strong><br>
													Milana Rakića 120<br>
                                                                                                        Beograd
												</p>
											</div>
										</div>
										<!-- ICON BLOCK : end -->
                                                                                
                                                                                <!-- ICON BLOCK : begin -->
										<div class="c-icon-block">
											<i class="ico fa fa-phone"></i>
											<div class="icon-block-inner">
												<p>
													<strong>Telefoni za zakazivanje</strong><br>
													+381 64 3494 929<br>
                                                                                                        +381 11 3423 979
												</p>
											</div>
										</div>
										<!-- ICON BLOCK : end -->

										<!-- ICON BLOCK : begin -->
										<div class="c-icon-block">
											<i class="ico fa fa-clock-o"></i>
											<div class="icon-block-inner">
                                                                                             <?php if($sitemapPage['body']) { 
                                                                                                 
                                                                                                    echo $sitemapPage['body'] ;
                                                                                                   
                                                                                            } ?>
                                                                                            
											</div>
										</div>
										<!-- ICON BLOCK : end -->

									</div>
								</div>

							</section>
							<!-- ADDRESS SECTION : end -->

							<!-- FORM SECTION : begin -->
							<section>
                                                            <div class="row">
                                                                <div class="col-lg-12">
                                                                    <?php echo $this->systemMessagesFront($this->systemMessages);?>
                                                                </div>
                                                            </div>
								<h2>Pošaljite nam poruku</h2>

								<div class="row">
									<div class="col-lg-8">

										<!-- CONTACT FORM : begin -->
										<form id="contact-form" class="default-form m-ajax-form" method="post" >
											<input type="hidden" name="contact-form">

											<!-- FORM VALIDATION ERROR MESSAGE : begin -->
											<p class="c-alert-message m-warning m-validation-error" style="display: none;"><i class="ico fa fa-exclamation-circle"></i>Molimo Vas popunite sva obavezna (*) polja.</p>
											<!-- FORM VALIDATION ERROR MESSAGE : end -->

											<!-- SENDING REQUEST ERROR MESSAGE : begin -->
											<p class="c-alert-message m-warning m-request-error" style="display: none;"><i class="ico fa fa-exclamation-circle"></i>There was a connection problem. Try again later.</p>
											<!-- SENDING REQUEST ERROR MESSAGE : end -->
                                                                                        
											<div class="row">
												<div class="col-sm-6">

													<!-- NAME FIELD : begin -->
													<div class="form-field">
														<label for="contact-name">Vaše ime <span>*</span></label>
                                                                                                                 <?php
                                                                                                                echo $form->getElement('first_name')->setAttribs(array(
                                                                                                                    'class' => 'm-required',
                                                                                                                    'placeholder' => 'Vaše ime',
                                                                                                                    'id' => 'contact-name',
                                                                                                                    'required' => 'required'
                                                                                                                ));
                                                                                                                ?>
													</div>
													<!-- NAME FIELD : end -->
                                                                                                        <br>
                                                                                                         <?php if ($form->getElement('first_name')->hasErrors()) { ?>
                                                                                                                        <p class="c-alert-message m-warning">
                                                                                                                            <?php foreach ($form->getElement('first_name')->getMessages() as $message) { ?>
                                                                                                                                <i class="ico fa fa-exclamation-circle"></i><?php echo $this->escape($message); ?>
                                                                                                                            <?php } ?>
                                                                                                                         </p>
                                                                                                                    <?php } ?>
                                                                                                        
													<!-- EMAIL FIELD : begin -->
													<div class="form-field">
														<label for="contact-email">Vaša Email Adresa <span>*</span></label>
														<input id="contact-email" name="contact-email" class="m-required m-email">
													</div>
													<p style="display: none;">
														<label for="contact-email-hp">Re Email Address</label>
														<input id="contact-email-hp" name="contact-email-hp">
													</p>
													<!-- EMAIL FIELD : end -->

													<!-- PHONE FIELD : begin -->
													<div class="form-field">
														<label for="contact-phone">Vaš broj telefona</label>
														<input id="contact-phone" name="contact-phone">
													</div>
													<!-- PHONE FIELD : end -->

												</div>
												<div class="col-sm-6">

													<!-- SUBJECT FIELD : begin -->
													<div class="form-field">
														<label for="contact-subject">Naslov poruke</label>
														<input id="contact-subject" name="contact-subject">
													</div>
													<!-- SUBJECT FIELD : end -->

													<!-- MESSAGE FIELD : begin -->
													<div class="form-field">
														<label for="contact-message">Poruka <span>*</span></label>
														<textarea id="contact-message" name="contact-message" class="m-required"></textarea>
													</div>
													<!-- MESSAGE FIELD : end -->

													<!-- SUBMIT BUTTON : begin -->
													<div class="form-field">
														<button class="submit-btn c-button" type="submit" data-label="Send Message" data-loading-label="Sending...">Pošalji poruku</button>
													</div>
													<!-- SUBMIT BUTTON : end -->

												</div>
											</div>

										</form>
										<!-- CONTACT FORM : end -->

									</div>
									
								</div>

							</section>
							<!-- FORM SECTION : end -->

						</div>
					</div>
					<!-- PAGE CONTENT : end -->

				</div>

			</div>
			<!-- CORE : end -->